### ISSUE TITLE
Warning on heroku-builds plugin install

### ISSUE THREAD

**Issue by mobilutz** [heroku/heroku-builds#104]
When running `heroku plugins:install heroku-builds` there is a warning output because of old `uuid` version:
```
warning heroku-builds > uuid@3.2.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

If I had some time, I would open a PullRequest, but time is not there right now 😦

**Comment by eablack** [comment]
Thanks, we elected to switch to `node:crypto`.
