### ISSUE TITLE
plugin can't be installed

### ISSUE THREAD

**Issue by Roguelazer** [heroku/heroku-builds#110]
```
$ heroku plugins:install heroku-builds
Installing plugin heroku-builds... failed
 ›   Error: plugin is invalid
```

**Comment by Roguelazer** [comment]
Odd, this just started working again. 10 failed installs in a row, then a success. Did you change something on your end...?

**Comment by afbelardi** [comment]
I'm having the same issue except mine still isn't working after trying multiple times

**Comment by mars** [comment]
What version of the CLI are you using? `heroku --version`

**Comment by mars** [comment]
V8.0.3 of the Heroku CLI has been released and intended to fix this.

**Comment by Roguelazer** [comment]
Any idea when https://github.com/heroku/homebrew-brew will be updated with 8.x?

**Comment by afbelardi** [comment]
> V8.0.3 of the Heroku CLI has been released and intended to fix this.

Ok, I'm currently running 8.0.2

**Comment by edmorley** [comment]
This should now be resolved. If anyone still sees this error message, run `heroku update` first and try again.
