### ISSUE TITLE
Really large builds

### ISSUE THREAD

**Issue by ysimonson** [heroku/heroku-builds#18]
I tried getting this up and running against a really simple app (1 Procfile, 4 python files, 2 txt files), and it produced a build that was >200mb. What would cause this?

Maybe .git directories aren't ignored, as per [here](https://github.com/heroku/heroku-builds/issues/2)? However, that app doesn't have a .git directory (although its parent directory does.)

**Comment by bbc2** [comment]
It looks like version 0.0.13 of heroku-builds doesn't take `.gitignore` into account. The problem doesn't occur with v0.0.12, which I rolled back to with:

```bash
heroku plugins:uninstall heroku-builds
git clone https://github.com/heroku/heroku-builds.git
cd heroku-builds
git checkout v0.0.12
npm install
heroku plugins:link
```

**Comment by bbc2** [comment]
I missed that your issue is from 2016 while I think that the issue I mentioned is more recent. I'll open a separate issue.  Sorry for the noise.

**Comment by dmathieu** [comment]
Could you check which are the large files?

> heroku run bash
> du -a /app | sort -n -r | head -n 10

**Comment by ysimonson** [comment]
I unfortunately don't have access to any of this now, since it was a long time ago. Closing this out.
