### ISSUE TITLE
Fatal error on Heroku Toolbelt 3.43.0

### ISSUE THREAD

**Issue by joshuarh** [heroku/heroku-builds#19]
When attempting to run `heroku builds:create` on Heroku Toolbelt 3.43.0 I get the following error:

```
buffer.js:106
      throw new Error(
      ^

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:106:13)
    at Readable.<anonymous> (/Users/Tend/.local/share/heroku/plugins/node_modules/archiver/lib/util/index.js:32:15)
    at emitNone (events.js:91:20)
    at Readable.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

We rely on this plugin for our build process and I'm happy to make a fix if I can. I'd love some insight into where to start looking. Any ideas?

**Comment by dickeyxxx** [comment]
Likely this is an issue with node 6

**Comment by dickeyxxx** [comment]
it is, with a dependency: https://github.com/archiverjs/node-archiver/issues/187

**Comment by joshuarh** [comment]
Interesting, thanks for looking into it!

It looks like they've released `1.2.0` but I'm still getting the error - does anything need to be updated/upgraded in order to take advantage of the change?

**Comment by dickeyxxx** [comment]
yeah the dep needs to be updated here, I'll work up a PR

**Comment by joshuarh** [comment]
Awesome! 🎉  Thanks so much for your quick response @dickeyxxx. One hopefully last question here: when I run `heroku plugins:install heroku-builds` it still installs 0.0.11 rather than the newly released 0.0.12. 

I've tried `heroku plugins:install https://github.com/heroku/heroku-builds` and `heroku plugins:install heroku-builds@0.0.12` both to no avail.

Any ideas on how we get heroku to pick up the new version?

**Comment by dickeyxxx** [comment]
sorry about that, try now

**Comment by joshuarh** [comment]
We're back in action! You rock @dickeyxxx, this really helps us out a lot. Thanks again.
