### ISSUE TITLE
Respect .gitignore and don't upload .git

### ISSUE THREAD

**Issue by friism** [heroku/heroku-builds#2]

**Comment by ysimonson** [comment]
Isn't .gitignore already respected? The README seems to suggest as such, and it seems like there's code to do it here: https://github.com/heroku/heroku-builds/blob/master/commands/builds/create.js#L14

**Comment by dmathieu** [comment]
We're handling this now, ignoring git ignored files.

**Comment by davidfurlong** [comment]
Is there a way to add gitignored files? For instance our build directory needs to be uploaded, but we don't want it to be committed to git. Also google cloud keys. I'm getting around this by having uncommitted removals of these lines in our gitignores, but thats not a great solution

**Comment by dmathieu** [comment]
The `--include-vcs-ignore=false` option will let you do that.

**Comment by davidfurlong** [comment]
Splendid thank you @dmathieu !

**Comment by dmathieu** [comment]
This is documented if you run `heroku builds:create --help`.
No, there is no way to ignore some files outside of those ignored by GIT.
