### ISSUE TITLE
Allow following symlinks

### ISSUE THREAD

**Issue by jeremyhaile** [heroku/heroku-builds#25]
The `tar` command supports a `-L/-h` option (follow symlinks) 

In my case I have some shared code within the project that I want deployed to heroku, but since it is a symlink, heroku-builds is not including it in the tar archive it builds.

We should add an option that tells the archiver to follow symlinks so these will be included in the archive.

**Comment by dmathieu** [comment]
I don't think we can do this.
Dynos only accept paths within `/app`. Following symlinks means we'd have  a tar with files expected to be outside the app folder, which won't be used by the runtime.
