### ISSUE TITLE
Failing with "https is required for source_blob:url"

### ISSUE THREAD

**Issue by jeremyhaile** [heroku/heroku-builds#27]
Running command: 
heroku builds:create -a appname --source-url=tmp/deploy.tar

Results in:
https is required for source_blob:url

We haven't made any changes on our end that we're aware of. This was working yesterday. I'm not sure what this error means.

**Comment by dmathieu** [comment]
Jeremy,

We did cut a new release yesterday. And it looks like bb9a9bf0ad00146b4e80aa49379e9df0d2079d5c wasn't in any release before then.

The issue here appears to be with your `source-url`. You're not passing an URL, but a path.
Are you trying to upload only a specific file? Because that argument would have been ignored previously.

Could you try running that command again, without the `source-url` argument?

Thanks

**Comment by jeremyhaile** [comment]
@dmathieu Yes, we were trying to upload local tar file as our release. We do this so that we can ensure our deploy script checks out the correct branch and does not include any local, uncommitted changes.  Is there a way to tell heroku-builds to use a local tar file as the upload?  Can you use a "file:///" url?

**Comment by dmathieu** [comment]
No.
What this plugin does is compress your app folder, upload it using our [sources api](https://devcenter.heroku.com/articles/platform-api-reference#source) and create a new build with the URL available.

When you specify `source-url`, we send the value directly to our API, which won't be able to download `file://` URLs.

However, you might just be using the wrong CLI plugin.
Have you taken a look at this one? https://devcenter.heroku.com/articles/deploying-executable-jar-files

**Comment by jeremyhaile** [comment]
@dmathieu Basically what we're trying to do is deploy a subdirectory of our repo to Heroku. Using a subtree is way too slow, so we use "git archive" to extract a tar file of the right branch. Then are trying to deploy that tar file to Heroku. 

Ideally, we could tell heroku builds to deploy the sources from our tar file instead of the local app folder (which might contain uncommitted changes)

Perhaps we could unpack the tar file, then repack it as a jar and deploy using the jar plugin you sent, but it's not a Java app but Rails. And this feels cumbersome.

Perhaps we could untar the file, and then use heroku builds to "re-tar" that tmp folder and upload it.

Have you seen this approach used? Would appreciate any advice on the best way of achieving this.

**Comment by dmathieu** [comment]
Jeremy,

The best way to achieve this would probably be to use our API directly.
You would do the following:

* Create your tar archive locally (be sure to use GNU tar).
* Create a new [source object](https://devcenter.heroku.com/articles/platform-api-reference#source-create) and upload your tar there using the put_url attribute.
* Create a [new build](https://devcenter.heroku.com/articles/platform-api-reference#build-create) passing the get_url from sources as the source_blob:url attribute in the request.

The build creation request will return a json object which contains an `output_stream_url` attribute. If you get on that URL, you will be able to stream the build output back.
