### ISSUE TITLE
Undefined path to current working directory

### ISSUE THREAD

**Issue by lucasm-iRonin** [heroku/heroku-builds#32]
Hi,
When I use this plugin on OS X with `gnu-tar` installed from Homebrew I get the following output:

```
 ▸    Command failed: /usr/local/bin/gtar cz -C undefined --exclude .git --exclude .gitmodules . >
 ▸    /var/folders/r1/c_lfj_yd1bq94qwvfdr6rq0m0000gn/T/36ccb936-e453-45e9-bdb0-8fce8d19894b.tar.gz
 ▸    /usr/local/bin/gtar: undefined: Cannot open: No such file or directory
 ▸    /usr/local/bin/gtar: Error is not recoverable: exiting now
```

It looks like path to current working directory is incorrect. I have `undefined` instead of `.`

**Comment by dmathieu** [comment]
@ransombriggs @dickeyxxx it looks like [context.cwd](https://github.com/heroku/heroku-builds/blob/master/commands/builds/create.js#L60) is undefined.
Has something changed in cli-utils requiring a change on this plugin?

**Comment by ransombriggs** [comment]
@dmathieu This is a change in `v6` that requires a change, changing `context.cwd` to `process.cwd()` should fix the bug.  Sorry that we did not catch this usage.

**Comment by ransombriggs** [comment]
@dmathieu I shipped https://github.com/heroku/heroku-builds/pull/33 to fix this

**Comment by ransombriggs** [comment]
@lucasm-iRonin could you run `heroku update` and try again?

**Comment by lucasm-iRonin** [comment]
@ransombriggs thank you for really quick fix! Yes indeed it works for me.

I've found another issue though - #34 , sorry for that :).

**Comment by dmathieu** [comment]
Thank you Ransom!
