### ISSUE TITLE
Heroku builds does not include id and builds:output is blank

### ISSUE THREAD

**Issue by lucasm-iRonin** [heroku/heroku-builds#34]
According to the readme `heroku builds` should include builds ID (`heroku builds -a example-app # take note of the build ID you'd want to display`) however in my case it looks like this:

```
2017/05/31 07:41:28 +0200 (~ 12s ago)  7436d5d0c0374ef43938db05ad46685322b61557  lukasz.mendelowski@ironin.pl
```

Where `7436d5d0c0374ef43938db05ad46685322b61557` is latest's commit SHA which I passed to `--version` argument.

As you can see there is no build's ID I can extract and pass to heroku `builds:output` command. Even if I take the id from activity page and pass it there, output is blank.

**Comment by dmathieu** [comment]
Thank you for reporting this. I've opened a PR adding the id back.

**Comment by lucasm-iRonin** [comment]
@dmathieu has this fix been released yet? After running `heroku update` I'm still not able to see the build's id.

Quick lookup to `~/.local/share/heroku/plugins/node_modules/heroku-builds/commands/builds/index.js` file shows that it does not have change introduced in #35 (`{key: 'id', format: (t) => t},`).

**Comment by dmathieu** [comment]
No, this has been merged but no new version of the plugin has been released.

**Comment by dmathieu** [comment]
Lucas,
I just shipped a new version of the plugin. Running `heroku update` should get you on it.

**Comment by lucasm-iRonin** [comment]
Thanks for update! I confirm it shows build ids correctly.
