### ISSUE TITLE
Exits without building instead of falling back to Node tar

### ISSUE THREAD

**Issue by rgrove** [heroku/heroku-builds#38]
Howdy! I'm using heroku-builds 0.0.14 on macOS with Node.js 8.0.0.

`heroku builds:create` prints the following output and then exits immediately:

```
 ▸    Couldn't detect GNU tar. Builds could fail due to decompression errors
 ▸    See https://devcenter.heroku.com/articles/platform-api-deploying-slugs#create-slug-archive
 ▸    Please install it, or specify the '--tar' option
 ▸    Falling back to node's built-in compressor
```

It sounds like the intent is to fall back to using Node to generate a tarball, but that doesn't seem to be happening. Any ideas?

**Comment by dmathieu** [comment]
Thank you for reporting this Ryan. I've opened a fix.

**Comment by dmathieu** [comment]
This fix has now been shipped, and I've released a new version of the plugin.

**Comment by rgrove** [comment]
Thanks!

**Comment by rgrove** [comment]
Hmm. Actually, I've tried 0.0.15 now and it still seems to have the same issue.

**Comment by dmathieu** [comment]
Could you run it with HEROKU_DEBUG=1 and paste the full output here?

**Comment by rgrove** [comment]
```
Executing /Users/rgrove/.local/share/heroku/cli/bin/heroku
heroku-cli/5.11.0-0c9c92b (darwin-amd64) go1.7.5 /Users/rgrove/.local/share/heroku/cli/bin/heroku cmd: builds:create
--> POST /apps/[redacted]/sources
--> {}
<-- 201 Created
<-- {"source_blob":{"get_url":"https://s3-external-1.amazonaws.com/heroku-sources-production/[redacted]?AWSAccessKeyId=[redacted]&Signature=[redacted]&Expires=1496434355","put_url":"https://s3-external-1.amazonaws.com/heroku-sources-production/[redacted]?AWSAccessKeyId=[redacted]&Signature=[redacted]&Expires=1496434355"}}
 ▸    Couldn't detect GNU tar. Builds could fail due to decompression errors
 ▸    See https://devcenter.heroku.com/articles/platform-api-deploying-slugs#create-slug-archive
 ▸    Please install it, or specify the '--tar' option
 ▸    Falling back to node's built-in compressor
```

**Comment by dmathieu** [comment]
Could you run `heroku update` and try again?
If it still doesn't work, could you paste here the output of the `heroku plugins` command?

**Comment by rgrove** [comment]
Ahh, I see now that I was on a really old version of the CLI. Apparently `heroku update` was just silently doing nothing since I had installed via Homebrew, so I didn't realize I was out of date. I had to upgrade via Homebrew instead.

After upgrading to heroku-cli/6.7.4-97fc5c6 I got a little further, but heroku-builds now fails for a new reason (which has an easy workaround; see below):

```
--> POST /apps/[redacted]/sources
--> {}
<-- 201 Created
<-- {"source_blob":{"get_url":"https://s3-external-1.amazonaws.com/heroku-sources-production/[redacted]?AWSAccessKeyId=[redacted]&Signature=[redacted]&Expires=1496702625","put_url":"https://s3-external-1.amazonaws.com/heroku-sources-production/[redacted]?AWSAccessKeyId=[redacted]&Signature=[redacted]&Expires=1496702625"}}
 ▸    Couldn't detect GNU tar. Builds could fail due to decompression errors
 ▸    See https://devcenter.heroku.com/articles/platform-api-deploying-slugs#create-slug-archive
 ▸    Please install it, or specify the '--tar' option
 ▸    Falling back to node's built-in compressor
Error: ENOENT: no such file or directory, open '.gitignore'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.call (/Users/rgrove/.local/share/heroku/plugins/node_modules/heroku-builds/lib/node_tar.js:10:30)
    at compressSource (/Users/rgrove/.local/share/heroku/plugins/node_modules/heroku-builds/commands/builds/create.js:30:13)
    at /Users/rgrove/.local/share/heroku/plugins/node_modules/heroku-builds/commands/builds/create.js:38:5
    at _fulfilled (/Users/rgrove/.local/share/heroku/plugins/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/rgrove/.local/share/heroku/plugins/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/rgrove/.local/share/heroku/plugins/node_modules/q/q.js:816:13)
    at /Users/rgrove/.local/share/heroku/plugins/node_modules/q/q.js:624:44
    at runSingle (/Users/rgrove/.local/share/heroku/plugins/node_modules/q/q.js:137:13)
Exiting with code: 1
```

Output of `heroku plugins` in case it's useful:

```
heroku-builds 0.0.15
heroku-container-registry 4.1.3
```

I'm running `heroku builds:create` from a build artifact directory that isn't a git repo, thus the lack of a `.gitignore` file. When I add an empty `.gitignore` file, the build succeeds and is deployed successfully.

Thanks for your help!

**Comment by dmathieu** [comment]
Thank you. I think this has been an issue for quite a while. I've opened #40 anyway.

Note that, as advised by the warning, you should use gnu-tar for compiling your app, not the fallback to node tar.
Using it means your app could start to fail building at any moment without a very good explanation as we might be unable to decompress the file.

**Comment by dmathieu** [comment]
Ryan,
I just pushed a new version of the plugin with the fix for the gitignore file.

**Comment by rgrove** [comment]
Thanks!
