### ISSUE TITLE
Silent failure when tar execution fails

### ISSUE THREAD

**Issue by bbc2** [heroku/heroku-builds#41]
The `tar --exclude-vcs-ignores` problem is known (https://github.com/heroku/heroku-builds/issues/36) and partially solved with the `--include-vcs-ignore` option. However, I'd like to point out that when the tar execution fails, its return status is 0:
```
> heroku builds:create --app myapp
tar: unrecognized option '--exclude-vcs-ignores'
Try 'tar --help' or 'tar --usage' for more information.
> echo $?
0
```

This makes deploys silently fail in CI and can thus be very surprising. What about returning a non-zero status code to avoid that?

**Comment by dmathieu** [comment]
Could you upgrade to 0.0.17? I just tried this, and it appears to work now.

**Comment by bbc2** [comment]
Yes it works now.  Thanks!
