### ISSUE TITLE
Move repo:purge_cache to heroku-builds

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-builds#52]
Hi!

As discussed in heroku/cli#509 and heroku/heroku-repo#69, it seems like the heroku-repo plugin isn't the best fit for the cache related command `repo:purge_cache`, particularly now that the caches are no longer tied to the git repo.

As such, heroku-builds seems like a good home, perhaps in the form of `builds:purge-cache` or `heroku builds:cache:purge`.

The existing code is here:
https://github.com/heroku/heroku-repo/blob/3e7167d79ca06f8be9cc4b084f7ca03d5adaee46/commands/purge_cache.js
https://github.com/heroku/heroku-repo/blob/3e7167d79ca06f8be9cc4b084f7ca03d5adaee46/lib/repo.js#L15-L16

Note there are some open tickets against this feature:
* heroku/heroku-repo#70: repo:purge_cache doesn't purge all files
* heroku/heroku-repo#61: Incorrect error with non-existent app name
* heroku/heroku-repo#57: Error: stdin: not in gzip format
* heroku/heroku-repo#36: repo:purge_cache when there is nothing to purge

Plus https://github.com/heroku/cli/pull/509#issuecomment-309892255 identified the following cleanups:
* rename command to something better
* show example of usage including output
* description is unclear and has improper grammar
* description verb should be 'delete' not 'deletes'

After this move, I'd also like to add a command to download the cache file for debugging (similar to the `slugs:download` command from [heroku-slugs](https://github.com/heroku/heroku-slugs)) - so worth bearing in mind for the naming.

I also wonder whether the `slugs:*` commands from [heroku-slugs](https://github.com/heroku/heroku-slugs) should be moved under the "builds" topic too, once builds covers {builds, cache, ...}?

**Comment by dmathieu** [comment]
The old command is now deprecated, and will be removed someday in the future.
