### ISSUE TITLE
ERROR: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by leemhenson** [heroku/heroku-builds#6]
```
$ heroku builds
ERROR: runtime error: invalid memory address or nil pointer dereference
$
```

and 

```
$ heroku builds:create
ERROR: runtime error: invalid memory address or nil pointer dereference
$
```

from

```
$ heroku version
heroku-toolbelt/3.30.0 (x86_64-darwin10.8.0) ruby/1.9.3
heroku-cli/4.12.1-a0a8d51 (amd64-darwin) go1.4.2
=== Installed Plugins
heroku-builds@0.0.2
heroku-repo
```

**Comment by dickeyxxx** [comment]
I think this is an issue attempting to read your .netrc file. Does anything look strange in it by chance?

**Comment by dickeyxxx** [comment]
you could post it or send it to me after scrubbing the keys out for security reasons

**Comment by leemhenson** [comment]
```
$ cat ~/.netrc
machine code.heroku.com
  login <my login>
  password <my password>
```

**Comment by dickeyxxx** [comment]
ah ha, if you run `heroku login` it should fill in the other parts and you should be able to use the plugin. I need to fix this though by making that happen automatically.

**Comment by leemhenson** [comment]
Hmm, nothing changed in my netrc:

```
$ heroku login
Authentication successful.
updating...done. Updated to 3.30.6
$ cat ~/.netrc
machine code.heroku.com
  login <my login>
  password <my password>
$
```

**Comment by leemhenson** [comment]
FYI My ```~/.netrc``` is actually a symlink into my dotfiles repo, if that has anything to do with it?

**Comment by dickeyxxx** [comment]
oh maybe, though if that's the problem it is a bug

**Comment by dickeyxxx** [comment]
mind trying again? I put a fix around the auth stuff here

**Comment by leemhenson** [comment]
Progress, but doesn't seem to support accounts with 2FA:

```
$ heroku builds
Enter your Heroku credentials.
Email: <my email>
Password (typing will be hidden):  !    A second authentication factor or pre-authorization is required for this request. Your account has either two-factor or a YubiKey registered.
```

**Comment by dmathieu** [comment]
2FA support has vastly improved in the past 2 years (it would also be an issue with core cli, not this plugin).
I'm going to close this issue. Please reopen if this still occurs.
