### ISSUE TITLE
Builds silently don't do anything

### ISSUE THREAD

**Issue by davidfurlong** [heroku/heroku-builds#62]
Sometimes (unreliably) it just gets stuck at (without showing build started  on my heroku dashboard). The process doesn't exit.

```
heroku builds:create -a deedmob-production-server
 ▸    Couldn't detect GNU tar. Builds could fail due to decompression errors
 ▸    See https://devcenter.heroku.com/articles/platform-api-deploying-slugs#create-slug-archive
 ▸    Please install it, or specify the '--tar' option
 ▸    Falling back to node's built-in compressor
```

My version is 0.0.20

Is there a debug flag or an upgrade command?

**Comment by dmathieu** [comment]
Could you try with `HEROKU_DEBUG=1 heroku builds:create -a deedmob-production-server`?

**Comment by davidfurlong** [comment]
> Could you try with HEROKU_DEBUG=1 heroku builds:create -a deedmob-production-server?

I'll try that next time it doesn't work, and report back

**Comment by dmathieu** [comment]
Closing as stale. Please let us know if this still happens.
