### ISSUE TITLE
builds:cache:purge command fails with "Invalid credentials provided"

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-builds#67]
Even though my credentials are valid (all other CLI commands work), I get:
```
$ heroku builds:cache:purge --app treeherder-stage --confirm treeherder-stage
Purging build cache for treeherder-stage... !
 !    Invalid credentials provided.
Enter your Heroku credentials:
Email:
```

This is using:
heroku-cli/6.15.17-49e98a1 (win32-x64) node-v9.3.0
heroku-api-plugin 2.1.4
heroku-buildkits 1.0.3
heroku-builds 0.0.23
heroku-slugs 1.0.3

**Comment by dmathieu** [comment]
@edmorley could you run the command with `HEROKU_DEBUG=1` and paste the full output?

**Comment by edmorley** [comment]
Hi! I get:
```
$ HEROKU_DEBUG=1 heroku builds:cache:purge --app treeherder-stage --confirm treeherder-stage
--> DELETE /apps/treeherder-stage/build-cache
Purging build cache for treeherder-stage... -
<-- 401 Unauthorized
Purging build cache for treeherder-stage... !
 !    Invalid credentials provided.
Enter your Heroku credentials:
Email:
```

(There's no rush with this since I can use heroku-repo in the meantime - do enjoy the rest of your weekend :-))

**Comment by dmathieu** [comment]
Thanks, and sorry for the regression. I just shipped a fix.

**Comment by edmorley** [comment]
Working great now - thank you :-)
