### ISSUE TITLE
Build returns succesfully despite failed push

### ISSUE THREAD

**Issue by bbc2** [heroku/heroku-builds#70]
On 0.0.24, he exit code of `builds:create` is 0 although the build failed (and is reported as such by Heroku):

```
-----> Python app detected
-----> Installing pip
 !     Push rejected, failed to compile Python app.

 !     Push failed
```

This causes the CI to wrongly believe deployment was successful.

**Comment by dmathieu** [comment]
Please open a support ticket, so we can inspect your app and provide you with better help.

**Comment by dmathieu** [comment]
Ah actually, I think I see what you mean. The issue is that the exit code returned is 0 even though the build failed.
Nice find.

**Comment by bbc2** [comment]
Yes, exactly.  By the way, I don't know where the Python issue came from.  Using a forked app or upgrading the Heroku stack solved the build failure in my case.  Anyway, it could happen again in the future so making the CI report correctly in such cases would be very nice.
