### ISSUE TITLE
Unexpected error when installing heroku-builds

### ISSUE THREAD

**Issue by jivinivan** [heroku/heroku-builds#77]
error An unexpected error occurred: "http://cli-npm.heroku.com/heroku-repo/-/heroku-repo-1.0.11/7319c9defc239ae783c2dd4c1f719b395b1fc01c.tgz: Request failed \"404 Not Found\"".

**Comment by jivinivan** [comment]
Looks related to this issue https://github.com/heroku/heroku-repo/issues/85

**Comment by dmathieu** [comment]
cc @heroku/cli

**Comment by RasPhilCo** [comment]
Delete the yarn.lock file `$ rm ~/.local/heroku/yarn.lock` then try reinstalling.
