### ISSUE TITLE
heroku-builds prompts for credentials when using SSO

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-builds#79]
Hi

When using SSO, credentials expire after 8 hours. When this happens, most heroku-cli commands act like so (I'm using the beta CLI channel):

```
$ heroku ps
 !    Invalid credentials provided.
heroku: Press any key to open up the browser to login or q to exit:
Logging in... done
...
```

However the heroku-build commands do not:

```
$ heroku builds:cache:purge --confirm treeherder-prod
Purging build cache for treeherder-prod... !
 !    Invalid credentials provided.
Enter your Heroku credentials:
Email:
```

I'm presuming heroku-builds needs to switch to using one of the newer heroku-cli helper libraries?

This is using:
heroku/7.18.4-beta.9813a43 win32-x64 node-v11.0.0
heroku-builds 0.0.27

**Comment by dmathieu** [comment]
cc @heroku/cli

**Comment by jaguaru** [comment]
Try this

sudo heroku login -i

**Comment by edmorley** [comment]
Logging in manually works fine and is the workaround I've been using so far. This issue is about making this command automatically prompt for login when needed, to avoid the need for that step at all.

**Comment by jdxcode** [comment]
you're correct @edmorley, [heroku-cli-util](https://github.com/heroku/heroku-builds/blob/master/package.json#L25) needs to be updated to the latest then it should work like other commands
