### ISSUE TITLE
heroku builds:create allow option to download failed slug

### ISSUE THREAD

**Issue by econner** [heroku/heroku-builds#82]
Is it possible to somehow download the slug from a build that fails because the slug size is too big?

My slug size randomly jumped up by 200 mb (without me changing anything) and I can't figure out why. Seems like some change to a buildpack is causing it, but I cannot compare the failed builds to the successful builds to see what changed. All of the cache purging mechanisms do not help.

Thanks.

**Comment by dmathieu** [comment]
No, this is not possible. When the build fails, we don't store the slug anywhere.

**Comment by dmathieu** [comment]
You may want to open a support ticket at help.heroku.com to get further help on this.

**Comment by econner** [comment]
I figured out my issue, but having something like this would have helped. Maybe it would be possible to have some mechanism for building and downloading a slug in the case it is too big. Seems to be a common need.
