### ISSUE TITLE
How to see which files are included in the build?

### ISSUE THREAD

**Issue by theronic** [heroku/heroku-builds#85]
I have a file at `./lib/heroku.js` which is specified in my Procfile as:

`web: node lib/heroku.js`

It runs when I call `heroku local web`, but when I deploy the current directory using `heroku builds:create`, Heroku throws `Error: Cannot find module '/app/lib/heroku.js'`

What's going on here? How do I see which files have been included in the build, and/or test the build locally?

(There is no .gitignore file in this folder.)

**Comment by dmathieu** [comment]
`builds:create` doesn't keep the build locally. You can see the files within your released app by running `heroku run bash` and then analyzing the content with that bash instance.

I'm going to close this issue, as it's not one with this plugin. I would recommend opening a support ticket instead.
